### ISSUE TITLE
add network cleanup to exit callback to fix infinite exit loop

### ISSUE THREAD

**Issue by noche-x** [NT-Bourgeois-Iridescence-Technologies/Stardust-Engine#20]
if you don't cleanup the driver before you exit it will be stuck on the exit screen.

**Comment by IridescentRose** [comment]
If only libc exited all threads like it's supposed to :P

**Comment by noche-x** [comment]
this only occurs on psplink. still annoying tho

**Comment by IridescentRose** [comment]
It appears that network cleanup will still not happen if you exit via `reset` - I'll still add a check
