### ISSUE TITLE
I'm so excited to see someone make an engine for psp

### ISSUE THREAD

**Issue by History-exe** [NT-Bourgeois-Iridescence-Technologies/Stardust-Engine#8]
- I have used [pgm](https://github.com/History-exe/Pocket-Game-Maker-v0.83) engine to make 2D adv [games](https://twitter.com/History_exe/status/954981022415728640) for psp, but due to my lack of technical level, there are many problems with pgm engine, which I cannot solve. So the production has come to an end for the time being. Today I am so excited to see someone making a new game engine for the PSP.

- If you need to add other language translations for the engine later, I can assist in translating the Chinese version.

**Comment by IridescentRose** [comment]
Thank you. I appreciate the excitement and I hope you do well on your programming journey. However, I do wish to ask that you don't create issues on Github for the purpose of simple discussion without any code errors. For that you can go to the PSP Homebrew Server #stardust channel to discuss projects and other things. https://discord.gg/bePrj9W
